import * as admin from "firebase-admin";

const getDb = () => admin.firestore();

export const DEFAULT_CATEGORIES = [
  {
    id: "cat_1",
    name: "Fresh Fruits & Vegetable",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=300",
    bgColor: 4293851121,
    borderColor: 4283674997,
  },
  {
    id: "cat_2",
    name: "Cooking Oil & Ghee",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300",
    bgColor: 4294832616,
    borderColor: 4294485068,
  },
  {
    id: "cat_3",
    name: "Meat & Fish",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=300",
    bgColor: 4294830308,
    borderColor: 4294419859,
  },
  {
    id: "cat_4",
    name: "Bakery & Snacks",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300",
    bgColor: 4294241271,
    borderColor: 4292063456,
  },
  {
    id: "cat_5",
    name: "Dairy & Eggs",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300",
    bgColor: 4294964964,
    borderColor: 4294829464,
  },
  {
    id: "cat_6",
    name: "Beverages",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=300",
    bgColor: 4293785596,
    borderColor: 4290240501,
  },
];

export const DEFAULT_PRODUCTS = [
  // ==========================================
  // 1. FRESH FRUITS & VEGETABLES (25 items)
  // ==========================================
  {
    id: "p_1",
    name: "Organic Bananas",
    description: "Naturally sweet and rich in potassium, perfect for daily breakfast and snacks.",
    unit: "7pcs, Bundle",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 142,
    nutritionInfo: "100gr ~ 89 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_2",
    name: "Red Apple",
    description: "Crisp and juicy handpicked Washington red apples with rich fiber content.",
    unit: "1kg, Pack",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.9,
    reviewsCount: 220,
    nutritionInfo: "100gr ~ 52 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_3",
    name: "Bell Pepper Red",
    description: "Sweet, crunchy red bell peppers packed with Vitamin C and natural antioxidants.",
    unit: "1kg, Pack",
    price: 2.99,
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.6,
    reviewsCount: 88,
    nutritionInfo: "100gr ~ 31 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 45,
    active: true,
  },
  {
    id: "p_4",
    name: "Ginger Root",
    description: "Aromatic and pungent organic ginger, essential for home cooking and health remedies.",
    unit: "250g, Pack",
    price: 1.99,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 65,
    nutritionInfo: "100gr ~ 80 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 30,
    active: true,
  },
  {
    id: "p_5",
    name: "Broccoli Florets",
    description: "Farm-fresh green broccoli crowns loaded with fiber, minerals, and Vitamin K.",
    unit: "500g, Pack",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 94,
    nutritionInfo: "100gr ~ 34 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_6",
    name: "Organic Carrots Bunch",
    description: "Sweet and crunchy tender garden carrots, perfect for salads, juicing, and soups.",
    unit: "1kg, Bunch",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 112,
    nutritionInfo: "100gr ~ 41 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 55,
    active: true,
  },
  {
    id: "p_7",
    name: "Baby Spinach Leaves",
    description: "Pre-washed tender baby spinach leaves, ideal for green smoothies and crisp salads.",
    unit: "250g, Box",
    price: 2.99,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.9,
    reviewsCount: 135,
    nutritionInfo: "100gr ~ 23 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 35,
    active: true,
  },
  {
    id: "p_8",
    name: "Hass Avocados",
    description: "Creamy, nutrient-dense ripe Hass avocados full of heart-healthy omega fats.",
    unit: "3pcs, Pack",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.9,
    reviewsCount: 240,
    nutritionInfo: "100gr ~ 160 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_9",
    name: "Roma Tomatoes",
    description: "Sun-ripened red plum Roma tomatoes with firm flesh, great for sauces and slicing.",
    unit: "1kg, Pack",
    price: 2.29,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.6,
    reviewsCount: 150,
    nutritionInfo: "100gr ~ 18 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 70,
    active: true,
  },
  {
    id: "p_10",
    name: "Sweet Potatoes",
    description: "Nutritious orange-fleshed sweet potatoes, delicious when roasted or baked.",
    unit: "1kg, Pack",
    price: 2.79,
    image: "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 78,
    nutritionInfo: "100gr ~ 86 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_11",
    name: "Fresh Yellow Lemons",
    description: "Zesty, aromatic lemons bursting with fresh citrus juice and Vitamin C.",
    unit: "500g, Net",
    price: 1.89,
    image: "https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 92,
    nutritionInfo: "100gr ~ 29 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_12",
    name: "Fresh Garlic Bulbs",
    description: "Plump organic garlic cloves with a pungent aroma and powerful culinary taste.",
    unit: "250g, Net",
    price: 1.69,
    image: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 80,
    nutritionInfo: "100gr ~ 149 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_13",
    name: "White Onions",
    description: "Crisp white onions with a sharp, clean bite that softens into savory sweetness.",
    unit: "1kg, Bag",
    price: 1.99,
    image: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.5,
    reviewsCount: 110,
    nutritionInfo: "100gr ~ 40 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 80,
    active: true,
  },
  {
    id: "p_14",
    name: "English Cucumbers",
    description: "Seedless crisp English cucumbers with thin skin, refreshing and hydrating.",
    unit: "2pcs, Pack",
    price: 2.19,
    image: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.6,
    reviewsCount: 88,
    nutritionInfo: "100gr ~ 15 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_15",
    name: "Organic Blueberries",
    description: "Plump, sweet, and antioxidant-rich fresh blueberries hand-sorted for quality.",
    unit: "170g, Box",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.9,
    reviewsCount: 180,
    nutritionInfo: "100gr ~ 57 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 35,
    active: true,
  },
  {
    id: "p_16",
    name: "Fresh Strawberries",
    description: "Vibrant red sweet strawberries with irresistible natural garden aroma.",
    unit: "250g, Box",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 165,
    nutritionInfo: "100gr ~ 32 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 45,
    active: true,
  },
  {
    id: "p_17",
    name: "Green Kiwi Fruit",
    description: "Tangy-sweet ripe green kiwis packed with natural Vitamin C and digestive enzymes.",
    unit: "6pcs, Pack",
    price: 3.29,
    image: "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 74,
    nutritionInfo: "100gr ~ 61 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_18",
    name: "Red Seedless Watermelon",
    description: "Crisp, sweet, and incredibly refreshing sliced red watermelon melon.",
    unit: "1 Whole (approx 3kg)",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 130,
    nutritionInfo: "100gr ~ 30 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 25,
    active: true,
  },
  {
    id: "p_19",
    name: "Navel Oranges",
    description: "Sweet, seedless, and easy-peeling juicy navel oranges from sunshine groves.",
    unit: "1kg, Bag",
    price: 3.79,
    image: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 145,
    nutritionInfo: "100gr ~ 47 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_20",
    name: "Red Seedless Grapes",
    description: "Firm, crisp red seedless grapes with delicious natural honey sweetness.",
    unit: "500g, Pack",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.9,
    reviewsCount: 160,
    nutritionInfo: "100gr ~ 69 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_21",
    name: "Green Cabbage",
    description: "Dense, crunchy green cabbage head, wonderful for coleslaw, stir-fries, and soups.",
    unit: "1 Head (approx 1kg)",
    price: 1.79,
    image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.5,
    reviewsCount: 62,
    nutritionInfo: "100gr ~ 25 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 35,
    active: true,
  },
  {
    id: "p_22",
    name: "White Cauliflower",
    description: "Tender, snow-white cauliflower florets, great for low-carb roasting and ricing.",
    unit: "1 Head",
    price: 2.99,
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.6,
    reviewsCount: 71,
    nutritionInfo: "100gr ~ 25 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 30,
    active: true,
  },
  {
    id: "p_23",
    name: "Green Bell Pepper",
    description: "Crisp, tangy green capsicum bell peppers, ideal for fajitas, pizzas, and stir-fries.",
    unit: "1kg, Pack",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.6,
    reviewsCount: 84,
    nutritionInfo: "100gr ~ 20 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_24",
    name: "Sweet Golden Corn",
    description: "Freshly harvested ears of sweet golden corn with tender, juicy kernels.",
    unit: "3pcs, Pack",
    price: 2.69,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.7,
    reviewsCount: 95,
    nutritionInfo: "100gr ~ 86 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_25",
    name: "Button Mushrooms",
    description: "Plump, earthy white button mushrooms, pre-cleaned and ready for sautés and pasta.",
    unit: "250g, Pack",
    price: 2.59,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
    category: "Fresh Fruits & Vegetable",
    rating: 4.8,
    reviewsCount: 110,
    nutritionInfo: "100gr ~ 22 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 40,
    active: true,
  },

  // ==========================================
  // 2. COOKING OIL & GHEE (15 items)
  // ==========================================
  {
    id: "p_26",
    name: "Pure Cow Ghee",
    description: "Traditional golden clarified butter with rich aroma and high smoke point for Indian cooking.",
    unit: "500ml, Jar",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1589927986086-3d10fb5b3e8a?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.9,
    reviewsCount: 310,
    nutritionInfo: "100ml ~ 900 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_27",
    name: "Extra Virgin Olive Oil",
    description: "First cold-pressed Mediterranean extra virgin olive oil with fruity notes.",
    unit: "1L, Bottle",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.9,
    reviewsCount: 290,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 45,
    active: true,
  },
  {
    id: "p_28",
    name: "Pure Mustard Oil",
    description: "Cold-pressed pungent kachi ghani mustard oil for authentic pickles and curries.",
    unit: "1L, Bottle",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.7,
    reviewsCount: 140,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_29",
    name: "Refined Sunflower Oil",
    description: "Light, odorless refined sunflower cooking oil with Vitamin E for daily frying.",
    unit: "1L, Pouch",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.6,
    reviewsCount: 185,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 80,
    active: true,
  },
  {
    id: "p_30",
    name: "Virgin Coconut Oil",
    description: "100% organic unrefined cold-pressed coconut oil for culinary baking and keto diets.",
    unit: "500ml, Jar",
    price: 6.49,
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.8,
    reviewsCount: 175,
    nutritionInfo: "100ml ~ 862 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_31",
    name: "Canola Cooking Oil",
    description: "Heart-friendly canola oil low in saturated fat, neutral flavor for baking and frying.",
    unit: "1L, Bottle",
    price: 4.29,
    image: "https://images.unsplash.com/photo-1541256942802-7b2996802927?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.6,
    reviewsCount: 110,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 55,
    active: true,
  },
  {
    id: "p_32",
    name: "Toasted Sesame Seed Oil",
    description: "Intensely fragrant dark roasted sesame oil, essential for Asian noodles and dressings.",
    unit: "250ml, Bottle",
    price: 5.49,
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.9,
    reviewsCount: 130,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 35,
    active: true,
  },
  {
    id: "p_33",
    name: "Cold-Pressed Peanut Oil",
    description: "Rich nutty groundnut oil with high heat stability, ideal for deep frying snacks.",
    unit: "1L, Can",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.7,
    reviewsCount: 95,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_34",
    name: "Physically Refined Rice Bran Oil",
    description: "Cholesterol-lowering Oryzanol enriched rice bran oil with high smoking point.",
    unit: "1L, Pouch",
    price: 4.19,
    image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.6,
    reviewsCount: 82,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_35",
    name: "Pure Avocado Cooking Oil",
    description: "Premium cold-pressed avocado oil with mild flavor and extreme 500°F smoke point.",
    unit: "500ml, Bottle",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.9,
    reviewsCount: 160,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 30,
    active: true,
  },
  {
    id: "p_36",
    name: "Desi Buffalo Ghee",
    description: "Traditional white buffalo milk ghee with thick grain and rich authentic country flavor.",
    unit: "500ml, Jar",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1589927986086-3d10fb5b3e8a?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.8,
    reviewsCount: 125,
    nutritionInfo: "100ml ~ 900 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_37",
    name: "Organic Safflower Oil",
    description: "Light golden high-oleic safflower oil, ideal for crisp salads and gentle sautéing.",
    unit: "750ml, Bottle",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.5,
    reviewsCount: 54,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 35,
    active: true,
  },
  {
    id: "p_38",
    name: "Walnut Culinary Oil",
    description: "Gourmet cold-pressed walnut oil for drizzling on pasta, grilled vegetables, and salads.",
    unit: "250ml, Bottle",
    price: 9.49,
    image: "https://images.unsplash.com/photo-1541256942802-7b2996802927?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.8,
    reviewsCount: 68,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 25,
    active: true,
  },
  {
    id: "p_39",
    name: "Grapeseed Oil",
    description: "Ultra clean, clean-tasting grapeseed oil that lets the flavors of your food shine.",
    unit: "500ml, Bottle",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.7,
    reviewsCount: 77,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_40",
    name: "Pure Corn Cooking Oil",
    description: "Classic golden corn oil offering excellent frying performance and balanced flavor.",
    unit: "1L, Bottle",
    price: 3.89,
    image: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400",
    category: "Cooking Oil & Ghee",
    rating: 4.5,
    reviewsCount: 88,
    nutritionInfo: "100ml ~ 884 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 60,
    active: true,
  },

  // ==========================================
  // 3. MEAT & FISH (15 items)
  // ==========================================
  {
    id: "p_41",
    name: "Grass-Fed Beef Bone In",
    description: "Premium cut fresh marrow bone and shank, ideal for gelatin-rich broths and hearty stews.",
    unit: "1kg, Cut",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 110,
    nutritionInfo: "100gr ~ 250 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 25,
    active: true,
  },
  {
    id: "p_42",
    name: "Farm Fresh Broiler Chicken",
    description: "Whole skinless broiler chicken cleaned and dressed, antibiotic-free and tender.",
    unit: "1kg, Whole",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400",
    category: "Meat & Fish",
    rating: 4.8,
    reviewsCount: 280,
    nutritionInfo: "100gr ~ 215 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_43",
    name: "Fresh Atlantic Salmon Fillets",
    description: "Sustainably farmed pink Atlantic salmon rich in healthy marine Omega-3 fatty acids.",
    unit: "400g, Pack",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 215,
    nutritionInfo: "100gr ~ 208 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 35,
    active: true,
  },
  {
    id: "p_44",
    name: "Tender Mutton Curry Cut",
    description: "Prime lean goat/mutton cuts on bone, trimmed fresh daily for succulent curries.",
    unit: "1kg, Pack",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 140,
    nutritionInfo: "100gr ~ 294 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 30,
    active: true,
  },
  {
    id: "p_45",
    name: "Jumbo King Prawns",
    description: "Peeled and deveined ocean king prawns with tail on, sweet firm texture.",
    unit: "500g, Pack",
    price: 13.49,
    image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400",
    category: "Meat & Fish",
    rating: 4.8,
    reviewsCount: 165,
    nutritionInfo: "100gr ~ 99 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 30,
    active: true,
  },
  {
    id: "p_46",
    name: "Yellowfin Tuna Steaks",
    description: "Thick cut sashimi-grade wild caught tuna steaks for high-heat searing.",
    unit: "350g, Pack",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400",
    category: "Meat & Fish",
    rating: 4.7,
    reviewsCount: 95,
    nutritionInfo: "100gr ~ 130 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 25,
    active: true,
  },
  {
    id: "p_47",
    name: "Boneless Chicken Breast",
    description: "Skinless, lean high-protein chicken breast cutlets, trimmed of excess fat.",
    unit: "1kg, Pack",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 310,
    nutritionInfo: "100gr ~ 165 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_48",
    name: "Lean Ground Beef (90/10)",
    description: "Freshly ground choice beef chuck with 10% fat content, perfect for smash burgers.",
    unit: "500g, Pack",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400",
    category: "Meat & Fish",
    rating: 4.8,
    reviewsCount: 190,
    nutritionInfo: "100gr ~ 217 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 45,
    active: true,
  },
  {
    id: "p_49",
    name: "Whole Mediterranean Sea Bass",
    description: "Cleaned and scaled whole sea bass with delicate, flaky white meat.",
    unit: "1 Fish (approx 600g)",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
    category: "Meat & Fish",
    rating: 4.7,
    reviewsCount: 82,
    nutritionInfo: "100gr ~ 97 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 20,
    active: true,
  },
  {
    id: "p_50",
    name: "Fresh Chicken Drumsticks",
    description: "Juicy, tender chicken leg drumsticks, mouth-watering when marinated and baked.",
    unit: "800g, Pack",
    price: 6.49,
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400",
    category: "Meat & Fish",
    rating: 4.8,
    reviewsCount: 155,
    nutritionInfo: "100gr ~ 172 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 55,
    active: true,
  },
  {
    id: "p_51",
    name: "Pasture-Raised Lamb Chops",
    description: "French trimmed lamb loin chops with delicate marbling and exceptional tenderness.",
    unit: "500g, Pack",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 98,
    nutritionInfo: "100gr ~ 258 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 20,
    active: true,
  },
  {
    id: "p_52",
    name: "Fresh Tilapia Fillets",
    description: "Mild white fish fillets, fast-cooking and versatile for pan-frying or fish tacos.",
    unit: "500g, Pack",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400",
    category: "Meat & Fish",
    rating: 4.6,
    reviewsCount: 112,
    nutritionInfo: "100gr ~ 96 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 35,
    active: true,
  },
  {
    id: "p_53",
    name: "Smoked Turkey Breast Slices",
    description: "Deli-style sliced smoked turkey breast, high protein and low sodium for lunchboxes.",
    unit: "200g, Pack",
    price: 4.29,
    image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400",
    category: "Meat & Fish",
    rating: 4.7,
    reviewsCount: 88,
    nutritionInfo: "100gr ~ 104 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_54",
    name: "Sweet Blue Crab Meat",
    description: "Pre-cooked lump crab meat, wild harvested and packed fresh for crab cakes.",
    unit: "220g, Tub",
    price: 16.49,
    image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400",
    category: "Meat & Fish",
    rating: 4.8,
    reviewsCount: 65,
    nutritionInfo: "100gr ~ 87 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 15,
    active: true,
  },
  {
    id: "p_55",
    name: "Wild Smoked Salmon Slices",
    description: "Thinly sliced cold-smoked salmon cured with sea salt and natural wood smoke.",
    unit: "150g, Pack",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
    category: "Meat & Fish",
    rating: 4.9,
    reviewsCount: 180,
    nutritionInfo: "100gr ~ 117 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 35,
    active: true,
  },

  // ==========================================
  // 4. BAKERY & SNACKS (15 items)
  // ==========================================
  {
    id: "p_56",
    name: "Whole Wheat Sliced Bread",
    description: "Hearty 100% whole grain loaf baked with natural grains and zero added artificial colors.",
    unit: "400g, Loaf",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    category: "Bakery & Snacks",
    rating: 4.7,
    reviewsCount: 210,
    nutritionInfo: "100gr ~ 247 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 65,
    active: true,
  },
  {
    id: "p_57",
    name: "Artisan Sourdough Loaf",
    description: "Slow-fermented artisan sourdough with crisp blistered crust and tangy airy crumb.",
    unit: "500g, Loaf",
    price: 4.29,
    image: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400",
    category: "Bakery & Snacks",
    rating: 4.9,
    reviewsCount: 175,
    nutritionInfo: "100gr ~ 238 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 30,
    active: true,
  },
  {
    id: "p_58",
    name: "French Butter Croissants",
    description: "Flaky, layered golden croissants made with pure creamy butter, baked fresh.",
    unit: "4pcs, Pack",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400",
    category: "Bakery & Snacks",
    rating: 4.9,
    reviewsCount: 230,
    nutritionInfo: "100gr ~ 406 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_59",
    name: "Sea Salt Kettle Potato Chips",
    description: "Crunchy batch-fried kettle potato chips tossed with pure natural sea salt.",
    unit: "150g, Bag",
    price: 2.19,
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400",
    category: "Bakery & Snacks",
    rating: 4.7,
    reviewsCount: 195,
    nutritionInfo: "100gr ~ 536 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 80,
    active: true,
  },
  {
    id: "p_60",
    name: "Soft Baked Chocolate Chip Cookies",
    description: "Rich chewy cookies packed with decadent melted Belgian chocolate chips.",
    unit: "8pcs, Box",
    price: 3.89,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400",
    category: "Bakery & Snacks",
    rating: 4.9,
    reviewsCount: 260,
    nutritionInfo: "100gr ~ 488 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_61",
    name: "Multigrain Pita Bread",
    description: "Pocket pita bread baked with flax, oats, and whole wheat for easy stuffing.",
    unit: "6pcs, Pack",
    price: 2.69,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    category: "Bakery & Snacks",
    rating: 4.6,
    reviewsCount: 88,
    nutritionInfo: "100gr ~ 260 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_62",
    name: "Organic Corn Tortilla Chips",
    description: "Crispy stone-ground yellow corn tortilla chips, ready for guacamole and salsa.",
    unit: "200g, Bag",
    price: 2.89,
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400",
    category: "Bakery & Snacks",
    rating: 4.7,
    reviewsCount: 120,
    nutritionInfo: "100gr ~ 490 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 60,
    active: true,
  },
  {
    id: "p_63",
    name: "Roasted Sea Salt Mixed Nuts",
    description: "Premium blend of roasted almonds, cashews, walnuts, and pecans with sea salt.",
    unit: "250g, Jar",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1536591375315-1b836814d48a?w=400",
    category: "Bakery & Snacks",
    rating: 4.9,
    reviewsCount: 195,
    nutritionInfo: "100gr ~ 607 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_64",
    name: "Wild Blueberry Muffins",
    description: "Moist bakery-style muffins bursting with sweet Maine wild blueberries.",
    unit: "4pcs, Pack",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=400",
    category: "Bakery & Snacks",
    rating: 4.8,
    reviewsCount: 140,
    nutritionInfo: "100gr ~ 360 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 35,
    active: true,
  },
  {
    id: "p_65",
    name: "Whole Grain Everything Bagels",
    description: "Chewy New York style bagels coated with sesame, poppy seeds, onion, and garlic.",
    unit: "5pcs, Bag",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400",
    category: "Bakery & Snacks",
    rating: 4.7,
    reviewsCount: 105,
    nutritionInfo: "100gr ~ 275 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_66",
    name: "Garlic & Herb Water Crackers",
    description: "Thin and crispy gourmet crackers seasoned with roasted garlic and fragrant herbs.",
    unit: "125g, Box",
    price: 2.29,
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=400",
    category: "Bakery & Snacks",
    rating: 4.6,
    reviewsCount: 76,
    nutritionInfo: "100gr ~ 440 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_67",
    name: "70% Dark Cocoa Chocolate Bar",
    description: "Single-origin Ecuadorian dark chocolate with silky melt and deep cocoa aroma.",
    unit: "100g, Bar",
    price: 3.29,
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400",
    category: "Bakery & Snacks",
    rating: 4.9,
    reviewsCount: 220,
    nutritionInfo: "100gr ~ 598 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_68",
    name: "Honey Almond Granola Bars",
    description: "Whole rolled oats, roasted almonds, and clover honey baked into crisp snack bars.",
    unit: "6 Bars, Box",
    price: 3.79,
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=400",
    category: "Bakery & Snacks",
    rating: 4.7,
    reviewsCount: 130,
    nutritionInfo: "100gr ~ 420 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 55,
    active: true,
  },
  {
    id: "p_69",
    name: "Cinnamon Swirl Brioche Bread",
    description: "Rich buttery French brioche swirled with sweet brown sugar cinnamon.",
    unit: "400g, Loaf",
    price: 4.69,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    category: "Bakery & Snacks",
    rating: 4.8,
    reviewsCount: 94,
    nutritionInfo: "100gr ~ 310 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 25,
    active: true,
  },
  {
    id: "p_70",
    name: "Traditional Salted Pretzels",
    description: "Crunchy oven-baked twisted pretzels sprinkled with coarse mineral sea salt.",
    unit: "200g, Bag",
    price: 1.99,
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400",
    category: "Bakery & Snacks",
    rating: 4.5,
    reviewsCount: 82,
    nutritionInfo: "100gr ~ 380 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 70,
    active: true,
  },

  // ==========================================
  // 5. DAIRY & EGGS (15 items)
  // ==========================================
  {
    id: "p_71",
    name: "Fresh Whole Milk",
    description: "Pure pasteurized farm fresh homogenized whole milk fortified with Vitamin D.",
    unit: "1L, Bottle",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 310,
    nutritionInfo: "100ml ~ 62 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 80,
    active: true,
  },
  {
    id: "p_72",
    name: "Organic Large Brown Eggs",
    description: "Grade-A pasture raised large brown eggs rich in Omega-3 and natural protein.",
    unit: "12pcs, Carton",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 285,
    nutritionInfo: "1 egg ~ 72 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 75,
    active: true,
  },
  {
    id: "p_73",
    name: "Greek Plain Strained Yogurt",
    description: "Thick, creamy authentic Greek yogurt with 15g protein per serving and zero added sugar.",
    unit: "500g, Tub",
    price: 3.79,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    category: "Dairy & Eggs",
    rating: 4.8,
    reviewsCount: 190,
    nutritionInfo: "100gr ~ 97 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_74",
    name: "Salted Sweet Cream Butter",
    description: "Slow-churned creamy dairy butter lightly salted with sea salt for spreading and cooking.",
    unit: "250g, Block",
    price: 3.29,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    category: "Dairy & Eggs",
    rating: 4.8,
    reviewsCount: 220,
    nutritionInfo: "100gr ~ 717 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_75",
    name: "Aged Sharp Cheddar Block",
    description: "Naturally aged 12-month English sharp cheddar cheese with complex savory bite.",
    unit: "200g, Block",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 165,
    nutritionInfo: "100gr ~ 403 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_76",
    name: "Fresh Cottage Cheese (Paneer)",
    description: "Soft, unsalted fresh cow milk paneer cubes packed with protein for curries and tikka.",
    unit: "400g, Pack",
    price: 4.29,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    category: "Dairy & Eggs",
    rating: 4.8,
    reviewsCount: 145,
    nutritionInfo: "100gr ~ 265 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 55,
    active: true,
  },
  {
    id: "p_77",
    name: "Unsweetened Almond Milk",
    description: "Smooth plant-based milk made from California almonds, dairy-free and only 30 calories.",
    unit: "1L, Carton",
    price: 3.19,
    image: "https://images.unsplash.com/photo-1568651316345-21d84877f0d0?w=400",
    category: "Dairy & Eggs",
    rating: 4.7,
    reviewsCount: 180,
    nutritionInfo: "100ml ~ 15 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_78",
    name: "Fresh Heavy Whipping Cream",
    description: "36% rich milkfat fresh cream, whips to stiff peaks for desserts, soups, and coffee.",
    unit: "250ml, Carton",
    price: 2.89,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    category: "Dairy & Eggs",
    rating: 4.8,
    reviewsCount: 95,
    nutritionInfo: "100ml ~ 340 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_79",
    name: "Fresh Mozzarella Cheese Ball",
    description: "Delicate Italian whole milk mozzarella ball packed in fresh brine, perfect for caprese.",
    unit: "200g, Tub",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 135,
    nutritionInfo: "100gr ~ 280 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 35,
    active: true,
  },
  {
    id: "p_80",
    name: "Mixed Berry Low-Fat Yogurt",
    description: "Creamy probiotic yogurt blended with real strawberries, raspberries, and blackberries.",
    unit: "4x100g, Pack",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    category: "Dairy & Eggs",
    rating: 4.7,
    reviewsCount: 110,
    nutritionInfo: "100gr ~ 85 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_81",
    name: "Farm Fresh Free-Range Eggs",
    description: "Certified humane free-range eggs laid by pasture roaming hens with golden yolks.",
    unit: "6pcs, Carton",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 140,
    nutritionInfo: "1 egg ~ 72 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 50,
    active: true,
  },
  {
    id: "p_82",
    name: "Organic Soy Milk Original",
    description: "Nutritious organic soy milk with 8g of complete plant protein per serving.",
    unit: "1L, Carton",
    price: 2.99,
    image: "https://images.unsplash.com/photo-1568651316345-21d84877f0d0?w=400",
    category: "Dairy & Eggs",
    rating: 4.6,
    reviewsCount: 92,
    nutritionInfo: "100ml ~ 54 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_83",
    name: "Aged Parmesan Wedge",
    description: "24-month aged Parmigiano Reggiano wedge with granular crystal texture and nutty finish.",
    unit: "150g, Wedge",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400",
    category: "Dairy & Eggs",
    rating: 4.9,
    reviewsCount: 170,
    nutritionInfo: "100gr ~ 431 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 40,
    active: true,
  },
  {
    id: "p_84",
    name: "Traditional Sour Cream",
    description: "Grade-A cultured sour cream, thick and tangy for baked potatoes, tacos, and dips.",
    unit: "250g, Tub",
    price: 2.19,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    category: "Dairy & Eggs",
    rating: 4.7,
    reviewsCount: 88,
    nutritionInfo: "100gr ~ 193 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_85",
    name: "Whipped Cream Cheese Spread",
    description: "Fluffy whipped cream cheese, spreads effortlessly on bagels, toast, and crackers.",
    unit: "220g, Tub",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    category: "Dairy & Eggs",
    rating: 4.8,
    reviewsCount: 115,
    nutritionInfo: "100gr ~ 342 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 45,
    active: true,
  },

  // ==========================================
  // 6. BEVERAGES (15 items)
  // ==========================================
  {
    id: "p_86",
    name: "Diet Coke Soda Can",
    description: "Crisp, zero-sugar refreshing carbonated soft drink served ice cold.",
    unit: "355ml, Can",
    price: 1.99,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    category: "Beverages",
    rating: 4.5,
    reviewsCount: 310,
    nutritionInfo: "355ml ~ 0 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 120,
    active: true,
  },
  {
    id: "p_87",
    name: "Sprite Sparkling Lemon Can",
    description: "Clear, crisp lemon-lime bubbly soda with 100% natural flavors and clean finish.",
    unit: "325ml, Can",
    price: 1.50,
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400",
    category: "Beverages",
    rating: 4.6,
    reviewsCount: 195,
    nutritionInfo: "325ml ~ 140 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 100,
    active: true,
  },
  {
    id: "p_88",
    name: "100% Pure Fresh Orange Juice",
    description: "Cold-pressed fresh Florida oranges with juicy pulp, high in natural Vitamin C.",
    unit: "1L, Bottle",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 240,
    nutritionInfo: "100ml ~ 45 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_89",
    name: "Pure Young Coconut Water",
    description: "Natural isotonic coconut water packed with electrolytes, potassium, and magnesium.",
    unit: "330ml, Carton",
    price: 2.49,
    image: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400",
    category: "Beverages",
    rating: 4.8,
    reviewsCount: 160,
    nutritionInfo: "100ml ~ 19 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 75,
    active: true,
  },
  {
    id: "p_90",
    name: "Cold Brew Unsweetened Coffee",
    description: "Slow-steeped Arabica coffee for 16 hours for an ultra-smooth, low-acidity energy boost.",
    unit: "320ml, Bottle",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 185,
    nutritionInfo: "100ml ~ 2 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_91",
    name: "Italian Sparkling Mineral Water",
    description: "Natural Italian mineral water naturally effervescent with fine crisp bubbles.",
    unit: "750ml, Glass Bottle",
    price: 2.89,
    image: "https://images.unsplash.com/photo-1560023907-5f339617ea30?w=400",
    category: "Beverages",
    rating: 4.8,
    reviewsCount: 140,
    nutritionInfo: "100ml ~ 0 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 70,
    active: true,
  },
  {
    id: "p_92",
    name: "Apple & Concord Grape Juice",
    description: "Sweet crisp apples blended with rich concord grapes, 100% juice with zero added sugar.",
    unit: "1.5L, Bottle",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 195,
    nutritionInfo: "100ml ~ 48 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 55,
    active: true,
  },
  {
    id: "p_93",
    name: "Organic Japanese Green Tea",
    description: "Premium Sencha green tea bags with smooth grassy aroma and gentle clean caffeine.",
    unit: "20 Bags, Box",
    price: 4.29,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400",
    category: "Beverages",
    rating: 4.8,
    reviewsCount: 120,
    nutritionInfo: "100ml ~ 1 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_94",
    name: "Southern Lemon Iced Tea",
    description: "Brewed black tea infused with sunny lemon juice and balanced natural cane sugar.",
    unit: "500ml, Bottle",
    price: 2.29,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    category: "Beverages",
    rating: 4.7,
    reviewsCount: 110,
    nutritionInfo: "100ml ~ 32 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 65,
    active: true,
  },
  {
    id: "p_95",
    name: "Alphonso Mango Nectar Juice",
    description: "Rich, luscious mango nectar made from the King of Mangoes, thick and full of flavor.",
    unit: "1L, Tetra Pack",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 210,
    nutritionInfo: "100ml ~ 55 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 60,
    active: true,
  },
  {
    id: "p_96",
    name: "Artisan Ginger Ale Soda",
    description: "Spicy brewed natural ginger ale made with real ginger root and subtle citrus notes.",
    unit: "4x330ml, Glass Pack",
    price: 5.49,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400",
    category: "Beverages",
    rating: 4.7,
    reviewsCount: 85,
    nutritionInfo: "100ml ~ 38 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 40,
    active: true,
  },
  {
    id: "p_97",
    name: "Organic Ginger Berry Kombucha",
    description: "Naturally fermented sparkling probiotic tea with tart berry infusion for gut health.",
    unit: "450ml, Bottle",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400",
    category: "Beverages",
    rating: 4.8,
    reviewsCount: 135,
    nutritionInfo: "100ml ~ 15 kcal",
    isExclusive: true,
    isBestSelling: false,
    stock: 35,
    active: true,
  },
  {
    id: "p_98",
    name: "Dark Roast Ground Coffee",
    description: "100% Arabica dark roast with deep dark chocolate and smoky toasted hazelnut notes.",
    unit: "340g, Bag",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 220,
    nutritionInfo: "100ml ~ 2 kcal",
    isExclusive: false,
    isBestSelling: true,
    stock: 50,
    active: true,
  },
  {
    id: "p_99",
    name: "Single-Serve Espresso Pods",
    description: "Compatible aluminum espresso pods delivering intense crema and full-bodied Italian taste.",
    unit: "10 Pods, Box",
    price: 6.49,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400",
    category: "Beverages",
    rating: 4.8,
    reviewsCount: 160,
    nutritionInfo: "100ml ~ 2 kcal",
    isExclusive: false,
    isBestSelling: false,
    stock: 45,
    active: true,
  },
  {
    id: "p_100",
    name: "100% Pomegranate Pure Juice",
    description: "Tart, deep ruby cold-pressed pomegranate juice without artificial sweeteners or preservatives.",
    unit: "1L, Bottle",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=400",
    category: "Beverages",
    rating: 4.9,
    reviewsCount: 175,
    nutritionInfo: "100ml ~ 65 kcal",
    isExclusive: true,
    isBestSelling: true,
    stock: 45,
    active: true,
  },
];

export const DEFAULT_PROMOS = [
  {
    code: "FRESH20",
    title: "20% OFF Fresh Produce",
    description: "Get 20% off on all organic vegetables and fresh fruits.",
    discountPercent: 20,
    discountAmount: 0,
    minSpend: 25.0,
    expiryDate: "2030-12-31T23:59:59.000Z",
    active: true,
  },
  {
    code: "GROCERY5",
    title: "$5 OFF First Order",
    description: "Flat $5 off on your first order over $30.",
    discountPercent: 0,
    discountAmount: 5.0,
    minSpend: 30.0,
    expiryDate: "2030-12-31T23:59:59.000Z",
    active: true,
  },
  {
    code: "SUPER10",
    title: "10% OFF Weekend Special",
    description: "Enjoy 10% off your entire grocery basket.",
    discountPercent: 10,
    discountAmount: 0,
    minSpend: 15.0,
    expiryDate: "2030-12-31T23:59:59.000Z",
    active: true,
  },
];

export async function seedInitialDatabase(): Promise<{
  categories: number;
  products: number;
  promos: number;
}> {
  const db = getDb();

  // 1. Commit categories (merge to avoid overwriting custom changes)
  const catBatch = db.batch();
  for (const cat of DEFAULT_CATEGORIES) {
    catBatch.set(
      db.collection("categories").doc(cat.id),
      {
        ...cat,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      {merge: true}
    );
  }
  await catBatch.commit();

  // 2. Commit 100 products in chunks (Firestore limit is 500 per batch)
  const chunkSize = 200;
  for (let i = 0; i < DEFAULT_PRODUCTS.length; i += chunkSize) {
    const chunk = DEFAULT_PRODUCTS.slice(i, i + chunkSize);
    const prodBatch = db.batch();
    for (const prod of chunk) {
      prodBatch.set(
        db.collection("products").doc(prod.id),
        {
          ...prod,
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        {merge: true}
      );
    }
    await prodBatch.commit();
  }

  // 3. Commit promo codes
  const promoBatch = db.batch();
  for (const promo of DEFAULT_PROMOS) {
    promoBatch.set(
      db.collection("promos").doc(promo.code),
      {
        ...promo,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      {merge: true}
    );
  }
  await promoBatch.commit();

  return {
    categories: DEFAULT_CATEGORIES.length,
    products: DEFAULT_PRODUCTS.length,
    promos: DEFAULT_PROMOS.length,
  };
}
