// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdwypKAUwf2xaYFazjYeafqM0wFymmzs',
    appId: '1:1071023352462:web:cfdbbbeb72906bc0c637df',
    messagingSenderId: '1071023352462',
    projectId: 'grocery-db70e',
    authDomain: 'grocery-db70e.firebaseapp.com',
    storageBucket: 'grocery-db70e.firebasestorage.app',
    measurementId: 'G-SKM2N539QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu2K2WQpLh7LyCWXKV9t94sgvsapqstZs',
    appId: '1:1071023352462:android:94cf7d0a6fe03534c637df',
    messagingSenderId: '1071023352462',
    projectId: 'grocery-db70e',
    storageBucket: 'grocery-db70e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlq8GlwqV61mZO8eLDSudL2sPrbsghVMg',
    appId: '1:1071023352462:ios:9d7a1c5875e36c4ec637df',
    messagingSenderId: '1071023352462',
    projectId: 'grocery-db70e',
    storageBucket: 'grocery-db70e.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlq8GlwqV61mZO8eLDSudL2sPrbsghVMg',
    appId: '1:1071023352462:ios:9d7a1c5875e36c4ec637df',
    messagingSenderId: '1071023352462',
    projectId: 'grocery-db70e',
    storageBucket: 'grocery-db70e.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfdwypKAUwf2xaYFazjYeafqM0wFymmzs',
    appId: '1:1071023352462:web:9b1697028053eebac637df',
    messagingSenderId: '1071023352462',
    projectId: 'grocery-db70e',
    authDomain: 'grocery-db70e.firebaseapp.com',
    storageBucket: 'grocery-db70e.firebasestorage.app',
    measurementId: 'G-J1S9B2TTEX',
  );
}
